Repository OntimizeWeb/ontimize-web-ngx-report, pull requests merged in 2023-11, with the labels that each got.

#149 Fixed bug that makes the menu button disappear
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.scss
Labels: bug

#160 Added subscriptSizing='dynamic' in mat-form-field
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/save-preferences-dialog/save-preferences-dialog.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/style-dialog/style-dialog.component.html
Labels: bug

#161 Replaced mat-line
  package-lock.json
  package.json
  projects/ontimize-web-ngx-report/package.json
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/apply-configuration/apply-configuration-dialog.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.html
Labels: bug

#164 Fixed bug that causes a vertical scroll
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.scss
Labels: bug

#169 [8.2.2] Added title as column name
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.ts
  projects/ontimize-web-ngx-report/src/lib/types/report-orderBy.type.ts
Labels: enhancement

#168 Hotfix 8.2.2
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-report/package.json
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.ts
  projects/ontimize-web-ngx-report/src/lib/types/report-orderBy.type.ts
Labels: release
