Repository OntimizeWeb/ontimize-web-ngx-report, pull requests merged in 2023-10, with the labels that each got.

#147 [15.x.x] Removed edit pdf option
  .github/workflows/build-release.yml
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-viewer/o-report-viewer.component.html
Labels: enhancement

#151 Added dark theme
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.ts
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-viewer/o-report-viewer.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-viewer/o-report-viewer.component.ts
Labels: enhancement

#153 [8.2.1] Fixed bug with action columns
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.ts
Labels: bug

#152 Hotfix 8.2.1
  .github/workflows/build-release.yml
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-report/package.json
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.ts
Labels: release
