Repository OntimizeWeb/ontimize-web-ngx-report, pull requests merged in 2024-01, with the labels that each got.

#176 Release 8.3.0
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-report/package.json
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.ts
  projects/ontimize-web-ngx-report/src/lib/config/o-providers.ts
  projects/ontimize-web-ngx-report/src/lib/interfaces/index.ts
  projects/ontimize-web-ngx-report/src/lib/interfaces/report-data-provider.interface.ts
  projects/ontimize-web-ngx-report/src/lib/interfaces/report-renderer.interface.ts
  projects/ontimize-web-ngx-report/src/lib/services/index.ts
  projects/ontimize-web-ngx-report/src/lib/services/ontimize-report-data-base-provider.service.ts
  projects/ontimize-web-ngx-report/src/lib/services/ontimize-report-data-provider.service.ts
Labels: release

#186 [8.3.1] Fixed bug that prevents groups from being cleaned
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.ts
Labels: bug

#187 [8.3.1] Added skeleton to report viewer
  package-lock.json
  package.json
  projects/ontimize-web-ngx-report/ng-package.json
  projects/ontimize-web-ngx-report/package.json
  projects/ontimize-web-ngx-report/src/lib/components/report/index.ts
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-skeleton/o-report-skeleton.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-skeleton/o-report-skeleton.component.scss
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-skeleton/o-report-skeleton.component.ts
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-viewer/o-report-viewer.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-viewer/o-report-viewer.component.ts
  projects/ontimize-web-ngx-report/src/lib/config/o-components.ts
Labels: bug

#189 [8.3.1] Modified report viewer style
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-detail/o-report-detail.component.ts
Labels: bug

#192 [8.3.1] Solved bug with service provider
  projects/ontimize-web-ngx-report/src/lib/config/o-providers.ts
Labels: bug

#181 Hotfix 8.3.1
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-report/ng-package.json
  projects/ontimize-web-ngx-report/package.json
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.ts
  projects/ontimize-web-ngx-report/src/lib/components/report/index.ts
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-detail/o-report-detail.component.ts
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-skeleton/o-report-skeleton.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-skeleton/o-report-skeleton.component.scss
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-skeleton/o-report-skeleton.component.ts
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-viewer/o-report-viewer.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report/o-report-viewer/o-report-viewer.component.ts
  projects/ontimize-web-ngx-report/src/lib/config/o-components.ts
  projects/ontimize-web-ngx-report/src/lib/config/o-providers.ts
Labels: release

#198 [8.3.2] Modified import in components.ts
  projects/ontimize-web-ngx-report/src/lib/config/o-components.ts
Labels: bug

#199 [8.3.2] CHANGELOG
  CHANGELOG.md
Labels: enhancement

#196 Hotfix 8.3.2
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-report/package.json
  projects/ontimize-web-ngx-report/src/lib/config/o-components.ts
Labels: release
