Repository OntimizeWeb/ontimize-web-ngx-report, pull requests merged in 2024-12, with the labels that each got.

#242 [Report-on-demand] Protected the preview button
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.ts
Labels: bug

#243 CHANGELOG 15.0.2
  CHANGELOG.md
Labels: enhancement

#240 Hotfix 15.0.2
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-report/package.json
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.html
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.ts
Labels: release

#248 [15.0.3] CHANGELOG
  CHANGELOG.md
Labels: enhancement

#245 Hotfix 15.0.3
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-report/package.json
  projects/ontimize-web-ngx-report/src/lib/components/report-on-demand/report-on-demand/report-on-demand.component.ts
Labels: release
